### ISSUE TITLE
microsoft/Florence-2-large is not the path to a directory containing a file named configuration_florence2.py

### ISSUE THREAD

**Issue by kuzhushidai** [miaoshouai/ComfyUI-Miaoshouai-Tagger#15]
We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like microsoft/Florence-2-large is not the path to a directory containing a file named configuration_florence2.py. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
大佬我想知道为啥我这里全部资源理应全部下载完毕了
但是会说文件里没有configuration_florence2.py
![292e9ef1-0630-4ee0-b203-c528e609ee24](https://github.com/user-attachments/assets/416ca9ab-e8b2-4d05-8fc8-947506c21e4f)

**Comment by kuzhushidai** [comment]
![Uploading 14649ce1-bfca-453f-a67f-2d6337eefda5.png…]()

**Comment by guoyouworld** [comment]
same issue

**Comment by richuyouyaojie** [comment]
the same issue here, kinldy solve it ASAP

**Comment by dx9052** [comment]
same issue

**Comment by uza0308** [comment]
same issue

**Comment by 2364814106** [comment]
same issue, is solved?

**Comment by miaoshouai** [comment]
ok. try to update to v1.3. model repo has added the configuration file to handle local model useage.
you can follow the instructions on the README.md to either auto download the model when re-run the workflow or download the model manually from baidu drive if huggingface is not reachable to you.

**Comment by miaoshouai** [comment]
![image](https://github.com/user-attachments/assets/49990058-7dd7-446d-a081-97523875bc67)
basicly this is the new folder you want to download and add with the new version of code.

**Comment by Rainmanqxy** [comment]
![image](https://github.com/user-attachments/assets/075fd04f-2cfd-496b-bdfe-a2236c244544)
Tried everything (download from Baidu, HuggingFace...), still can't run the node...everytime, the notice will pop up like this: 
![image](https://github.com/user-attachments/assets/ab4ea612-d754-4232-a3bc-c4beede18ccb)
Really like this node after seeing the introductions, but it's taken hours to install it but failed, a little frustrated... 
Please kindly help on this, thanks!

**Comment by Rainmanqxy** [comment]
Is there any limitation on the hardware?  I'm using N 4060Ti 16g...

**Comment by miaoshouai** [comment]
4060ti is good for the model. try to update your node again in comfyui manager. it was updated recently

**Comment by Linxiren** [comment]
我也是遇到了一样的问题，明明已经更新了节点，但是就是不起作用

**Comment by 807502278** [comment]
问题可能出在transformers的这个模块上AutoModelForCausalLM.from_pretrained()，
即使已指定本地文件，它仍然会自动下载3个py文件到缓存文件夹
![image](https://github.com/user-attachments/assets/c629109c-2b52-41f0-ad0b-5230e205f408)
而且使用cache_dir参数指定路径也会下
也许可以尝试更换transformers版本来解决此问题

**Comment by kaiday2023** [comment]
We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like microsoft/Florence-2-base-ft is not the path to a directory containing a file named processing_florence2.py.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by miaoshouai** [comment]
refer to this issue for the fix solusion: https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger/issues/23#issuecomment-2401340644
